# iOS CircleCI 2.0 configuration file

version: 2

jobs:
    build-and-test:
        macos:
            xcode: '10.2.0'

        steps:
            - checkout

            # Install CocoaPods
            - run:
                name: Install CocoaPods
                command: pod install

            # Build the app and run tests
            - run:
                name: Build and run tests
                command: xcodebuild test -scheme Stopwatch

            # Collect XML test results data to show in the UI,
            # and save the same XML files under test-results folder
            # in the Artifacts tab
            - store_test_results:
                path: test_output/report.xml
            - store_artifacts:
                path: /tmp/test-results
                destination: scan-test-results
            - store_artifacts:
                path: ~/Library/Logs/scan
                destination: scan-logs

    swiftlint:
        docker:
            - image: dantoml/swiftlint:latest
        steps:
            - checkout
            - run: swiftlint lint Stopwatch StopwatchTests StopwatchUITests --reporter junit | tee result.xml
            - store_artifacts:
                path: result.xml
            - store_test_results:
                path: result.xml

workflows:
    version: 2
    build-test-lint:
        jobs:
            - swiftlint
            - build-and-test
