version: 2

jobs:
    Test:
        macos:
            xcode: '10.2.0'

        steps:
            - checkout

            - run:
                name: Build and run tests
                command: xcodebuild -workspace StopwatchApp.xcworkspace -scheme CI -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2' test | xcpretty --report junit

            - store_test_results:
                path: build/reports/junit.xml
            - store_artifacts:
                path: build/reports/junit.xml

    SwiftLint:
        docker:
            - image: dantoml/swiftlint:latest

        steps:
            - checkout

            - run:
                name: Run SwiftLint
                command: mkdir test-results test-results/swiftlint && swiftlint lint Stopwatch StopwatchTests StopwatchUITests --reporter junit | tee test-results/swiftlint/result.xml

            - store_artifacts:
                path: test-results

            - store_test_results:
                path: test-results

    SwiftFormat:
        macos:
            xcode: '10.2.0'

        steps:
            - checkout
            - run:
                name: Verify SwiftFormat does not introduce changes
                command: ./Pods/SwiftFormat/CommandLineTool/swiftformat --exclude Pods --lint .

workflows:
    version: 2
    build-test-lint:
        jobs:
            - SwiftLint
            - SwiftFormat
            - Test
