#!/bin/bash
set -o pipefail

SCRIPT_DIR="$( cd "$( dirname "$0" )/.." && pwd )"
BEAUTIFY="$SCRIPT_DIR/Pods/xcbeautify/xcbeautify"

xcodebuild -workspace StopwatchApp.xcworkspace -scheme Stopwatch -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2' test -only-testing:StopwatchTests | $BEAUTIFY
